class AddMoredetailsToFormuliers < ActiveRecord::Migration[5.0]
  def change
    add_column :formuliers, :isolatieafplakken_maandag, :integer
    add_column :formuliers, :isolatieafplakken_dinsdag, :integer
    add_column :formuliers, :isolatieafplakken_woensdag, :integer
    add_column :formuliers, :isolatieafplakken_donderdag, :integer
    add_column :formuliers, :isolatieafplakken_vrijdag, :integer
    add_column :formuliers, :isolatieafplakken_totaal, :integer
    add_column :formuliers, :rollagen_maandag, :integer
    add_column :formuliers, :rollagen_dinsdag, :integer
    add_column :formuliers, :rollagen_woensdag, :integer
    add_column :formuliers, :rollagen_donderdag, :integer
    add_column :formuliers, :rollagen_vrijdag, :integer
    add_column :formuliers, :rollagen_totaal, :integer
    add_column :formuliers, :dilitatie_maandag, :integer
    add_column :formuliers, :dilitatie_dinsdag, :integer
    add_column :formuliers, :dilitatie_woensdag, :integer
    add_column :formuliers, :dilitatie_donderdag, :integer
    add_column :formuliers, :dilitatie_vrijdag, :integer
    add_column :formuliers, :dilitatie_totaal, :integer
    add_column :formuliers, :lateitot25_maandag, :integer
    add_column :formuliers, :lateitot25_dinsdag, :integer
    add_column :formuliers, :lateitot25_woensdag, :integer
    add_column :formuliers, :lateitot25_donderdag, :integer
    add_column :formuliers, :lateitot25_vrijdag, :integer
    add_column :formuliers, :lateitot25_totaal, :integer
    add_column :formuliers, :lateitot50_maandag, :integer
    add_column :formuliers, :lateitot50_dinsdag, :integer
    add_column :formuliers, :lateitot50_woensdag, :integer
    add_column :formuliers, :lateitot50_donderdag, :integer
    add_column :formuliers, :lateitot50_vrijdag, :integer
    add_column :formuliers, :lateitot50_totaal, :integer
    add_column :formuliers, :negge_maandag, :integer
    add_column :formuliers, :negge_dinsdag, :integer
    add_column :formuliers, :negge_woensdag, :integer
    add_column :formuliers, :negge_donderdag, :integer
    add_column :formuliers, :negge_vrijdag, :integer
    add_column :formuliers, :negge_totaal, :integer
    add_column :formuliers, :perinsul_maandag, :integer
    add_column :formuliers, :perinsul_dinsdag, :integer
    add_column :formuliers, :perinsul_woensdag, :integer
    add_column :formuliers, :perinsul_donderdag, :integer
    add_column :formuliers, :perinsul_vrijdag, :integer
    add_column :formuliers, :perinsul_totaal, :integer
    add_column :formuliers, :schragensteiger_maandag, :integer
    add_column :formuliers, :schragensteiger_dinsdag, :integer
    add_column :formuliers, :schragensteiger_woensdag, :integer
    add_column :formuliers, :schragensteiger_donderdag, :integer
    add_column :formuliers, :schragensteiger_vrijdag, :integer
    add_column :formuliers, :schragensteiger_totaal, :integer
    add_column :formuliers, :consoles_maandag, :integer
    add_column :formuliers, :consoles_dinsdag, :integer
    add_column :formuliers, :consoles_woensdag, :integer
    add_column :formuliers, :consoles_donderdag, :integer
    add_column :formuliers, :consoles_vrijdag, :integer
    add_column :formuliers, :consoles_totaal, :integer
    add_column :formuliers, :vloerrooster_maandag, :integer
    add_column :formuliers, :vloerrooster_dinsdag, :integer
    add_column :formuliers, :vloerrooster_woensdag, :integer
    add_column :formuliers, :vloerrooster_donderdag, :integer
    add_column :formuliers, :vloerrooster_vrijdag, :integer
    add_column :formuliers, :vloerrooster_totaal, :integer
    add_column :formuliers, :stootvoegrooster_maandag, :integer
    add_column :formuliers, :stootvoegrooster_dinsdag, :integer
    add_column :formuliers, :stootvoegrooster_woensdag, :integer
    add_column :formuliers, :stootvoegrooster_donderdag, :integer
    add_column :formuliers, :stootvoegrooster_vrijdag, :integer
    add_column :formuliers, :stootvoegrooster_totaal, :integer
    add_column :formuliers, :murfor_maandag, :integer
    add_column :formuliers, :murfor_dinsdag, :integer
    add_column :formuliers, :murfor_woensdag, :integer
    add_column :formuliers, :murfor_donderdag, :integer
    add_column :formuliers, :murfor_vrijdag, :integer
    add_column :formuliers, :murfor_totaal, :integer
    add_column :formuliers, :dpc_maandag, :integer
    add_column :formuliers, :dpc_dinsdag, :integer
    add_column :formuliers, :dpc_woensdag, :integer
    add_column :formuliers, :dpc_donderdag, :integer
    add_column :formuliers, :dpc_vrijdag, :integer
    add_column :formuliers, :dpc_totaal, :integer
    add_column :formuliers, :zagen_maandag, :integer
    add_column :formuliers, :zagen_dinsdag, :integer
    add_column :formuliers, :zagen_woensdag, :integer
    add_column :formuliers, :zagen_donderdag, :integer
    add_column :formuliers, :zagen_vrijdag, :integer
    add_column :formuliers, :zagen_totaal, :integer
    add_column :formuliers, :gasbeton_maandag, :integer
    add_column :formuliers, :gasbeton_dinsdag, :integer
    add_column :formuliers, :gasbeton_woensdag, :integer
    add_column :formuliers, :gasbeton_donderdag, :integer
    add_column :formuliers, :gasbeton_vrijdag, :integer
    add_column :formuliers, :gasbeton_totaal, :integer
    add_column :formuliers, :raamdorpel25_maandag, :integer
    add_column :formuliers, :raamdorpel25_dinsdag, :integer
    add_column :formuliers, :raamdorpel25_woensdag, :integer
    add_column :formuliers, :raamdorpel25_donderdag, :integer
    add_column :formuliers, :raamdorpel25_vrijdag, :integer
    add_column :formuliers, :raamdorpel25_totaal, :integer
    add_column :formuliers, :raamdorpel50_maandag, :integer
    add_column :formuliers, :raamdorpel50_dinsdag, :integer
    add_column :formuliers, :raamdorpel50_woensdag, :integer
    add_column :formuliers, :raamdorpel50_donderdag, :integer
    add_column :formuliers, :raamdorpel50_vrijdag, :integer
    add_column :formuliers, :raamdorpel50_totaal, :integer
    add_column :formuliers, :raamdorpel100_maandag, :integer
    add_column :formuliers, :raamdorpel100_dinsdag, :integer
    add_column :formuliers, :raamdorpel100_woensdag, :integer
    add_column :formuliers, :raamdorpel100_donderdag, :integer
    add_column :formuliers, :raamdorpel100_vrijdag, :integer
    add_column :formuliers, :raamdorpel100_totaal, :integer
    add_column :formuliers, :schuinte_maandag, :integer
    add_column :formuliers, :schuinte_dinsdag, :integer
    add_column :formuliers, :schuinte_woensdag, :integer
    add_column :formuliers, :schuinte_donderdag, :integer
    add_column :formuliers, :schuinte_vrijdag, :integer
    add_column :formuliers, :schuinte_totaal, :integer
    add_column :formuliers, :opmerkingen, :text
  end
end
