# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20180304152014) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "formuliers", force: :cascade do |t|
    t.integer  "weeknummer"
    t.date     "van"
    t.date     "tot"
    t.string   "naam_werknemer"
    t.string   "urenmaandag"
    t.string   "integer"
    t.integer  "urendinsdag"
    t.integer  "urenwoensdag"
    t.integer  "urendonderdag"
    t.integer  "urenvrijdag"
    t.integer  "urentotaal"
    t.datetime "created_at",                  null: false
    t.datetime "updated_at",                  null: false
    t.string   "plaats_werk"
    t.string   "aannemer"
    t.integer  "gevelsteen_maandag"
    t.integer  "gevelsteen_dinsdag"
    t.integer  "gevelsteen_woensdag"
    t.integer  "gevelsteen_donderdag"
    t.integer  "gevelsteen_vrijdag"
    t.integer  "gevelsteen_totaal"
    t.integer  "pointmasteren_maandag"
    t.integer  "pointmasteren_dinsdag"
    t.integer  "pointmasteren_woensdag"
    t.integer  "pointmasteren_donderdag"
    t.integer  "pointmasteren_vrijdag"
    t.integer  "pointmasteren_totaal"
    t.integer  "snelbouwsteen100_maandag"
    t.string   "snelbouwsteen100_dinsdag"
    t.string   "snelbouwsteen100_woensdag"
    t.integer  "snelbouwsteen100_donderdag"
    t.integer  "snelbouwsteen100_vrijdag"
    t.integer  "snelbouwsteen100_totaal"
    t.integer  "snelbouwsteen400_maandag"
    t.integer  "snelbouwsteen400_dinsdag"
    t.integer  "snelbouwsteen400_woensdag"
    t.integer  "snelbouwsteen400_donderdag"
    t.integer  "snelbouwsteen400_vrijdag"
    t.integer  "snelbouwsteen400_totaal"
    t.integer  "hardschuim_maandag"
    t.integer  "hardschuim_dinsdag"
    t.integer  "hardschuim_woensdag"
    t.integer  "hardschuim_donderdag"
    t.integer  "hardschuim_vrijdag"
    t.integer  "hardschuim_totaal"
    t.integer  "isolatieafplakken_maandag"
    t.integer  "isolatieafplakken_dinsdag"
    t.integer  "isolatieafplakken_woensdag"
    t.integer  "isolatieafplakken_donderdag"
    t.integer  "isolatieafplakken_vrijdag"
    t.integer  "isolatieafplakken_totaal"
    t.integer  "rollagen_maandag"
    t.integer  "rollagen_dinsdag"
    t.integer  "rollagen_woensdag"
    t.integer  "rollagen_donderdag"
    t.integer  "rollagen_vrijdag"
    t.integer  "rollagen_totaal"
    t.integer  "dilitatie_maandag"
    t.integer  "dilitatie_dinsdag"
    t.integer  "dilitatie_woensdag"
    t.integer  "dilitatie_donderdag"
    t.integer  "dilitatie_vrijdag"
    t.integer  "dilitatie_totaal"
    t.integer  "lateitot25_maandag"
    t.integer  "lateitot25_dinsdag"
    t.integer  "lateitot25_woensdag"
    t.integer  "lateitot25_donderdag"
    t.integer  "lateitot25_vrijdag"
    t.integer  "lateitot25_totaal"
    t.integer  "lateitot50_maandag"
    t.integer  "lateitot50_dinsdag"
    t.integer  "lateitot50_woensdag"
    t.integer  "lateitot50_donderdag"
    t.integer  "lateitot50_vrijdag"
    t.integer  "lateitot50_totaal"
    t.integer  "negge_maandag"
    t.integer  "negge_dinsdag"
    t.integer  "negge_woensdag"
    t.integer  "negge_donderdag"
    t.integer  "negge_vrijdag"
    t.integer  "negge_totaal"
    t.integer  "perinsul_maandag"
    t.integer  "perinsul_dinsdag"
    t.integer  "perinsul_woensdag"
    t.integer  "perinsul_donderdag"
    t.integer  "perinsul_vrijdag"
    t.integer  "perinsul_totaal"
    t.integer  "schragensteiger_maandag"
    t.integer  "schragensteiger_dinsdag"
    t.integer  "schragensteiger_woensdag"
    t.integer  "schragensteiger_donderdag"
    t.integer  "schragensteiger_vrijdag"
    t.integer  "schragensteiger_totaal"
    t.integer  "consoles_maandag"
    t.integer  "consoles_dinsdag"
    t.integer  "consoles_woensdag"
    t.integer  "consoles_donderdag"
    t.integer  "consoles_vrijdag"
    t.integer  "consoles_totaal"
    t.integer  "vloerrooster_maandag"
    t.integer  "vloerrooster_dinsdag"
    t.integer  "vloerrooster_woensdag"
    t.integer  "vloerrooster_donderdag"
    t.integer  "vloerrooster_vrijdag"
    t.integer  "vloerrooster_totaal"
    t.integer  "stootvloerrooster_maandag"
    t.integer  "stootvloerrooster_dinsdag"
    t.integer  "stootvloerrooster_woensdag"
    t.integer  "stootvloerrooster_donderdag"
    t.integer  "stootvloerrooster_vrijdag"
    t.integer  "stootvloerrooster_totaal"
    t.integer  "murfor_maandag"
    t.integer  "murfor_dinsdag"
    t.integer  "murfor_woensdag"
    t.integer  "murfor_donderdag"
    t.integer  "murfor_vrijdag"
    t.integer  "murfor_totaal"
    t.integer  "dpc_maandag"
    t.integer  "dpc_dinsdag"
    t.integer  "dpc_woensdag"
    t.integer  "dpc_donderdag"
    t.integer  "dpc_vrijdag"
    t.integer  "dpc_totaal"
    t.integer  "zagen_maandag"
    t.integer  "zagen_dinsdag"
    t.integer  "zagen_woensdag"
    t.integer  "zagen_donderdag"
    t.integer  "zagen_vrijdag"
    t.integer  "zagen_totaal"
    t.integer  "gasbeton_maandag"
    t.integer  "gasbeton_dinsdag"
    t.integer  "gasbeton_woensdag"
    t.integer  "gasbeton_donderdag"
    t.integer  "gasbeton_vrijdag"
    t.integer  "gasbeton_totaal"
    t.integer  "raamdorpel25_maandag"
    t.integer  "raamdorpel25_dinsdag"
    t.integer  "raamdorpel25_woensdag"
    t.integer  "raamdorpel25_donderdag"
    t.integer  "raamdorpel25_vrijdag"
    t.integer  "raamdorpel25_totaal"
    t.integer  "raamdorpel50_maandag"
    t.integer  "raamdorpel50_dinsdag"
    t.integer  "raamdorpel50_woensdag"
    t.integer  "raamdorpel50_donderdag"
    t.integer  "raamdorpel50_vrijdag"
    t.integer  "raamdorpel50_totaal"
    t.integer  "raamdorpel100_maandag"
    t.integer  "raamdorpel100_dinsdag"
    t.integer  "raamdorpel100_woensdag"
    t.integer  "raamdorpel100_donderdag"
    t.integer  "raamdorpel100_vrijdag"
    t.integer  "raamdorpel100_totaal"
    t.integer  "schuinte_maandag"
    t.integer  "schuinte_dinsdag"
    t.integer  "schuinte_woensdag"
    t.integer  "schuinte_donderdag"
    t.integer  "schuinte_vrijdag"
    t.integer  "schuinte_totaal"
  end

end
